sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG}:${TRAVIS_BUILD_NUMBER} docker
  - docker run -d -p 2379:2379 ${TRAVIS_REPO_SLUG}:${TRAVIS_BUILD_NUMBER}
  - docker ps -a

script:
  - until curl http://127.0.0.1:2379/version; do sleep 2; done
